# Generated by Django 4.1 on 2022-08-26 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuphistory',
            name='backup_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
